version: "2"

services:
  d-evermos:
    image: gcr.io/staging-256810/d-evermos:latest
    build:
      context: .
      dockerfile: dockerfiles/app.docker
    container_name: "d-evermos"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "80:8080"
    networks:
      - default
      - bridge-network
    links: 
      - redis
  redis:
      image: sickp/alpine-redis:3.2.2
      restart: unless-stopped
      ports:
          - "6380:6379"
  postgres:
      image: onjin/alpine-postgres:9.5
      restart: unless-stopped
      ports:
          - "5432:5432"
networks:
  default:
    driver: bridge
  bridge-network:
    external: true