INTERNAL_SERVER_ERROR:
  message: "{error}"

NOT_FOUND:
  message: "{resource} was not found."

INVALID_DATA:
  message: "There is some problem with the data you submitted. See \"details\" for more information."
